# Generated by Django 5.0.7 on 2024-07-18 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocomplete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocomplete',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
